<!-- include(./api-blueprints/__intro.apib) -->
<!-- include(./api-blueprints/_data_structures.apib) -->
<!-- include(./api-blueprints/_errors.apib) -->
<!-- include(./api-blueprints/categories.apib) -->
<!-- include(./api-blueprints/events.apib) -->
<!-- include(./api-blueprints/users.apib) -->