# Data Structures

## Image
- url: `https://images.unsplash.com/i-am-a-photo` (string)
- size
    - width: 100 (number)
    - height: 100 (number)


## Point
- coordinates (array)
    - `-123.100761` (number)
    - `49.280659` (number)
- type: `Point` (string)

## Location
- name: `I am a location` (string)
- location (Point)


## User
- _id: `aaaaaaaaaaaaaaaaaaaaaaaa` (string)
- _createdAt: `2020-05-01T14:00:00.000Z` (string)
- _updatedAt: `2020-05-01T14:00:00.000Z` (string)
- firstName: `I am a user` (string)
- lastName: `last name` (string)
- email: `randomuser@randomdomain.com` (string)
- username: `random_user123` (string)

## UserRequest100
+ firstName: `I am a new user` (string)
+ lastName: `last name` (string)
+ email: `randomuser@randomdomain.com` (string)
+ username: `random_user123` (string)

## UserRequest101
+ email: `noname@noname.com` (string)

## UserRequest200
+ firstName: `I am a newer user` (string)
+ lastName: `with last name` (string)
+ email: `rando@randomdomain.com` (string)

## UserRequest201
+ firstName: `I am a patched` (string)
+ lastName: `user` (string)
+ email: `odnar@domainrandom.com` (string)


## Event
- _id: `aaaaaaaaaaaaaaaaaaaaaaaa` (string)
- _createdAt: `2020-05-01T14:00:00.000Z` (string)
- _updatedAt: `2020-05-01T14:00:00.000Z` (string)
- hosts (array)
    - `5e880d3208b2ba001a08d82e` (string)
- name: `I am an event` (string)
- startDate: `2020-05-01T14:00:00.000Z` (string)
- endDate: `2020-05-01T14:00:00.000Z` (string)
- venue (Location)
- price: 100 (number)
- description: `I am the event's description.` (string)
- rating (object)
    - sum: 3.55 (number)
    - count: 1000 (number)
- categories (array)
    - `MUS` (string)
    - `OTH` (string)
- links (array)
    - (object)
        - name: `ticket` (string)
        - url: `https://fortunesoundclub.com/sup-fu-saturdays/` (string)
- media
    - coverPhoto (Image)
    - hostPhotos (array)
        - (Image)
    - userPhotos (array)
        - (Image)
- tags
    - hostTags (array)
        - `hip hop` (string)
        - `festival` (string)
    - userTags (array)
        - `drinks` (string)
        - `social` (string)

## EventRequest100
+ hosts (array)
    + `aaaaaaaaaaaaaaaaaaaaaaaa` (string)
+ name: `I am an event` (string)
+ startDate: `2020-05-01T14:00:00.000Z` (string)
+ endDate: `2020-05-01T14:00:00.000Z` (string)
+ venue (Location)
+ price: 100 (number)
+ description: `I am the event's description.` (string)
+ categories (array)
    + `MUS` (string)
+ links (array)
    + (object)
        + name: `ticket` (string)
        + url: `https://fortunesoundclub.com/sup-fu-saturdays/` (string)
+ coverPhoto (Image)
+ media (array)
    + (Image)
+ tags (array)
    + `hip hop` (string)
    + `festival` (string)

## EventRequest101
+ price: 100 (number)
+ description: `I am the event's description.` (string)
+ links (array)
    + (object)
        + name: `ticket` (string)
        + url: `https://fortunesoundclub.com/sup-fu-saturdays/` (string)
+ coverPhoto (Image)
+ media (array)
    + (Image)
+ tags (array)
    + `hip hop` (string)
    + `festival` (string)

## EventRequest102
+ hosts (array)
    + `aaaaaaaaaaaaaaaaaaaaaaaa` (string)
+ name: `I am an event` (string)
+ startDate: `2020-05-01T14:00:00.000Z` (string)
+ endDate: `2020-05-01T14:00:00.000Z` (string)
+ venue (Location)
+ price: 100 (number)
+ description: `I am the event's description.` (string)
+ categories (array)
    + `000000000000000000000000` (string)
+ links (array)
    + (object)
        + name: `ticket` (string)
        + url: `https://fortunesoundclub.com/sup-fu-saturdays/` (string)
+ coverPhoto (Image)
+ media (array)
    + (Image)
+ tags (array)
    + `hip hop` (string)
    + `festival` (string)

## EventRequest103
+ hosts (array)
+ name: `I am an event` (string)
+ startDate: `2020-05-01T14:00:00.000Z` (string)
+ endDate: `2020-05-01T14:00:00.000Z` (string)
+ venue (Location)
+ price: 100 (number)
+ description: `I am the event's description.` (string)
+ categories (array)
    + `aaaaaaaaaaaaaaaaaaaaaaaa` (string)
+ links (array)
    + (object)
        + name: `ticket` (string)
        + url: `https://fortunesoundclub.com/sup-fu-saturdays/` (string)
+ coverPhoto (Image)
+ media (array)
    + (Image)
+ tags (array)
    + `hip hop` (string)
    + `festival` (string)

## EventRequest104
+ hosts (array)
    + `aaaaaaaaaaaaaaaaaaaaaaaa` (string)
+ name: `I am an event` (string)
+ startDate: `2020-05-01T14:00:00.000Z` (string)
+ endDate: `2020-05-01T14:00:00.000Z` (string)
+ venue (Location)
+ price: 100 (number)
+ description: `I am the event's description.` (string)
+ categories (array)
    + `MUS` (string)
+ links (array)
    + (object)
        + name: `ticket` (string)
        + url: `https://fortunesoundclub.com/sup-fu-saturdays/` (string)
+ coverPhoto (Image)
+ media (array)
    + (Image)
+ tags (array)
    + `hip hop` (string)
    + `festival` (string)

## EventRequest200
+ hosts (array)
    + `000000000000000000000000` (string)
+ name: `I am an updated event`
+ startDate: `2020-05-01T14:00:00.000Z` (string)
+ endDate: `2020-05-01T14:00:00.000Z` (string)
+ venue (Location)
+ price: 299 (number)
+ description: `Updated Description.` (string)
+ rating (object)
    + sum: 3.55 (number)
    + count: 1000 (number)
+ categories (array)
    + `MUS` (string)
+ links (array)
    + (object)
        + name: `ticket` (string)
        + url: `https://fortunesoundclub.com/sup-fo-sundays/` (string)
+ media
    + coverPhoto (Image)
    + hostPhotos (array)
        + (Image)
+ tags (array)
    + hostTags (array)
        + `family` (string)
    + userTags (array)
        + 'user' (string)

## EventRequest201
+ name: `I am a patched event`
+ startDate: `2020-05-01T14:00:00.000Z` (string)
+ endDate: `2020-05-01T14:00:00.000Z` (string)
+ venue (Location)
+ price: 299 (number)
+ description: `Patched Description.` (string)
+ rating (object)
    + sum: 3.55 (number)
    + count: 1000 (number)
+ categories (array)
    + `OTH` (string)
+ links (array)
    + (object)
        + name: `ticket` (string)
        + url: `https://fortunesoundclub.com/sup-fi-sundays/` (string)
+ media (array)
    + (Image)
+ tags (array)
    + `fun` (string)
    + `friends` (string)

